-- CREATE SCHEMA IF NOT EXISTS usr;

CREATE TABLE IF NOT EXISTS users
(
    id     BIGSERIAL PRIMARY KEY,
    name   TEXT  NOT NULL,
    salt   BYTEA NOT NULL,
    secret BYTEA NOT NULL,
    UNIQUE (name)
);
