
###

POST localhost:8080/api/accounts
Accept: application/json
Content-Type: application/json
Authorization: 33bbdf5379d2459f89be37013fb3a610

{
  "name": "g",
  "owner": "g@g.com"
}

###

GET localhost:8080/api/accounts/1
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###

POST localhost:8080/api/users
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

{
  "name": "aaaa",
  "password": "sdfwexfaerfcsref"
}

###


GET localhost:8080/api/users/1
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###

GET localhost:8080/api/projects/39
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###

GET localhost:8080/api/projects
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###

GET localhost:8080/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###

GET localhost:8080/api/tasks/192
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###


GET localhost:8080/api/resources/
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###


GET localhost:8080/api/resources/38
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e


###

POST localhost:8081/tasks/demo
Accept: application/json
Content-Type: application/json
Authorization: 022c0d408e1842629d67b405ee3bc56e

###
