
###

POST localhost:8080/api/accounts
Accept: application/json
Content-Type: application/json

{
  "name": "g",
  "owner": "g@g.com"
}

###

GET localhost:8080/api/accounts/1
Accept: application/json
Content-Type: application/json

###

POST localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "aaaa",
  "password": "sdfwexfaerfcsref"
}

###


GET localhost:8080/api/users/1
Accept: application/json
Content-Type: application/json

###

GET localhost:8080/api/projects/2/2
Accept: application/json
Content-Type: application/json

###

GET localhost:8080/api/projects/2
Accept: application/json
Content-Type: application/json

###

POST localhost:8081/tasks/demo
Accept: application/json
Content-Type: application/json

###
