GET {{host}}/api/accounts/1
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

POST {{host}}/api/users
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "name": "aaaa",
  "password": "sdfwexfaerfcsref"
}

###

GET {{host}}/api/users/1
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/projects/39
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/projects
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/tasks/201
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/resources/
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/resources/44
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/skills
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET {{host}}/api/skills/75
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

POST localhost:8081/tasks/demo
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET localhost:3000/api/projects/view/2
Authorization: {{token}}
Accept: application/json
#Content-Type: application/json

###