
@startuml
'https://plantuml.com/sequence-diagram

interface User
interface Account
interface AccountUser
interface Token
enum Role

AccountUser -> User
AccountUser -left-> Account
AccountUser -up-> Role
Token -up-> User
Token -up-> Account

@enduml